import React from "react";
import desktopImage from "/public/Desktop2.jpg";
const CustomizationSection = () => {
  return (
    <div className="bg-white">
      <section
        className="relative w-full flex justify-center justify-content-center px-2 overflow-hidden flex-col  max-w-screen-2xl 
     main-wrapper"
      >
        <div className="relative z-10 max-w-screen-2xl w-full flex flex-col items-center  py-12 text-center pt-0">
          <h2 className="text-3xl sm:text-4xl md:text-5xl font-inter font-semibold leading-tight mb-4">
            One Platform, Infinite{" "}
            <span className="bg-gradient-to-r from-pink-500 to-purple-500 text-transparent bg-clip-text">
              Styles
            </span>
          </h2>
          <p className="max-w-2xl text-base sm:text-lg md:text-xl text-gray-700 mb-8">
            Explore real ads generated by Glowpilot for different brands,
            products, and platforms. Your next winning creative is just a prompt
            away.
          </p>
          <button className="button-style2 transition-all duration-300 hover:scale-105 hover:shadow-[0px_0px_20px_rgba(253,42,178,0.5),0px_0px_25px_rgba(113,65,210,0.5)]">
            Try Free
          </button>
        </div>
        <div>
          <img src={desktopImage} className="mx-auto w-[1290px]" />
        </div>
      </section>
    </div>
  );
};

export default CustomizationSection;
